openapi: 3.0.0
info:
  title: Employees API
  description: A simple API to manage employees
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local server

paths:
  /employees/common-projects:
    post:
      operationId: uploadEmployeesProjects
      summary: Accept CSV file with projects and employees for processing. Once processed return a list with employee pairs working on same projects.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: CSV file containing employee and project data
      responses:
        '202':
          description: File accepted for processing
        '400':
          description: File validation failed
        '413':
          description: File too large
        '500':
          description: Internal server error

  /employees/common-projects/result/{identification-process-id}:
    get:
      operationId: getCommonProjects
      summary: Fetch common projects by pair of employees
      parameters:
        - name: identification-process-id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: Unique identifier of the upload operation
      responses:
        '200':
          description: Common projects identification process found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommonProject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: string
                example: "Invalid request parameters"
        '404':
          description: Identification process not found
          content:
            application/json:
              schema:
                type: string
                example: "Identification process not found"

components:
  schemas:
    CommonProject:
      type: object
      properties:
        firstEmployeeId:
          type: integer
          example: 143
        secondEmployeeId:
          type: integer
          example: 218
        projectId:
          type: integer
          example: 12
        daysWorked:
          type: integer
          example: 60
